language: php

before_install:
  - echo 'hhvm.libxml.ext_entity_whitelist = file,http,https' > travis.hhvm.ini

addons:
  postgresql: "9.3"

php:
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - mkdir -p build/logs
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" -o "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then hhvm -c travis.hhvm.ini $HOME/.phpenv/versions/hhvm/bin/phpunit --verbose --coverage-text; else phpunit --verbose --coverage-text; fi;'

after_script:
  - php vendor/bin/coveralls -v
