language: php

before_install:
  - echo 'hhvm.libxml.ext_entity_whitelist = file,http,https' > travis.hhvm.ini

addons:
  postgresql: "9.3"

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then hhvm -c travis.hhvm.ini $HOME/.phpenv/versions/hhv/bin/phpunit; else phpunit --verbose; fi;'
