language: php

before_install:
  - composer self-update

php:
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --verbose --coverage-text

after_script:
  - php vendor/bin/coveralls -v
