language: php

addons:
  postgresql: "9.3"

php:
  - 5.5
  - 5.6
  - hhvm
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: phpunit --configuration phpunit.xml.dist
