language: php

sudo: false

php:
  - 7.2

before_script:
  - composer install
  - php -r "file_exists('.env') || copy('.env.example', '.env');"
  - php artisan key:generate
  - php artisan migrate

script:
  - ./vendor/bin/phpunit
