language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
    - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then echo -e '\nhhvm.libxml.ext_entity_whitelist = "xml.xsd"' | sudo tee -a /etc/hhvm/php.ini; fi

matrix:
  allow_failures:
  - php: hhvm-nightly

script: phpunit --configuration phpunit.xml.dist
