language: php

addons:
  postgresql: "9.3"

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - chmod +x ./library/Tricolore/Tests/Bootstrap/hhvm.sh
  - ./library/Tricolore/Tests/Bootstrap/hhvm.sh
  - psql -c 'create database travis_ci_test;' -U postgres

script: phpunit --configuration phpunit.xml.dist
