language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script: phpenv config-add config.ini

matrix:
  allow_failures:
  - php: hhvm-nightly

script: phpunit --configuration phpunit.xml.dist
