language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  - POSTGRESQL_VERSION=9.1
  - POSTGRESQL_VERSION=9.2
  - POSTGRESQL_VERSION=9.3
  - POSTGRESQL_VERSION=9.4

before_install:
  - echo 'hhvm.libxml.ext_entity_whitelist = file,http,https' > travis.hhvm.ini
  - composer self-update

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer install
  - sudo service postgresql stop
  - sudo service postgresql start $POSTGRESQL_VERSION
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - mkdir -p build/logs
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" -o "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then hhvm -c travis.hhvm.ini $HOME/.phpenv/versions/hhvm/bin/phpunit --verbose --coverage-text; else phpunit --verbose --coverage-text; fi;'

after_script:
  - php vendor/bin/coveralls -v
