prod:
    base.full_url: "http://php.dev/tricolore"
    base.locale: "en"
    base.charset: "utf-8"
    base.timezone: "Europe/Warsaw"
    base.log_exceptions: false

    router.host: ~
    router.use_httpd_rewrite: false

    cookie.path: ~
    cookie.domain: ~
    cookie.secure: false

    trans.locale: "en_EN"

    gzip.enabled: true

    directory.storage: "storage"
    directory.assets: "static"

    cache.provider: "PhpFile"
    cache.memcache.server: "127.0.0.1"
    cache.memcache.port: 11211
    cache.memcached.server: "127.0.0.1"
    cache.memcached.port: 11211
    cache.redis.server: "127.0.0.1"
    cache.redis.port: 6379

dev:
    base.full_url: "http://php.dev/tricolore"
    base.locale: "en"
    base.charset: "utf-8"
    base.timezone: "Europe/Warsaw"
    base.log_exceptions: false

    router.host: ~
    router.use_httpd_rewrite: true

    cookie.path: ~
    cookie.domain: ~
    cookie.secure: false

    trans.locale: "en_EN"

    gzip.enabled: false

    directory.storage: "storage"
    directory.assets: "static"

    cache.provider: "PhpFile"
    cache.memcache.server: "127.0.0.1"
    cache.memcache.port: 11211
    cache.memcached.server: "127.0.0.1"
    cache.memcached.port: 11211
    cache.redis.server: "127.0.0.1"
    cache.redis.port: 6379

test:
    base.full_url: "http://localhost/Tricolore/tests"
    base.locale: "en"
    base.charset: "utf-8"
    base.timezone: "Europe/Warsaw"

    router.use_httpd_rewrite: false

    trans.locale: "en_EN"

    test.int: 5874

    directory.storage: "storage"
    directory.assets: "static"