home:
    path: /
    methods: [GET]
    defaults: 
        _controller: Tricolore\Controller\Frontend\IndexAction:index

hello:
    path: /hello/{name}
    methods: [GET]
    requirements: 
        name: "[A-Za-z0-9-_]+"
    defaults: 
        _controller: Tricolore\Controller\Frontend\HelloAction:sayHello

auth:
    path: /auth
    methods: [GET, POST]
    defaults:
        _controller: Tricolore\Controller\Frontend\Auth:login

auth_logout:
    path: /auth/logout
    methods: [POST]
    defaults:
        _controller: Tricolore\Controller\Frontend\Auth:logout

register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: Tricolore\Controller\Frontend\Register:process

admincp_auth:
    path: /admincp/auth
    methods: [GET, POST]
    defaults:
        _controller: Tricolore\Controller\Backend\Auth:process