home:
    path: /
    methods: [GET]
    defaults: 
        _controller: Tricolore\Controller\Frontend\Index:index

kitchensink:
    path: /kitchensink
    methods: [GET]
    defaults: 
        _controller: Tricolore\Controller\Frontend\KitchenSink:woah

auth:
    path: /auth
    methods: [GET, POST]
    defaults:
        _controller: Tricolore\Controller\Frontend\Auth:login

auth_logout:
    path: /auth/logout
    methods: [POST]
    defaults:
        _controller: Tricolore\Controller\Frontend\Auth:logout

register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: Tricolore\Controller\Frontend\Register:process

admincp_auth:
    path: /admincp/auth
    methods: [GET, POST]
    defaults:
        _controller: Tricolore\Controller\Backend\Auth:process

installer_start:
    path: /installer
    methods: [GET]
    defaults:
        _controller: Tricolore\Controller\Installer\Install:start

installer_details:
    path: /installer/details
    methods: [GET, POST]
    defaults:
        _controller: Tricolore\Controller\Installer\Install:details