base.full_url: "http://localhost/Tricolore/develop"
base.locale: "en"
base.charset: "utf-8"

router.prefix: ~
router.host: ~
router.use_httpd_rewrite: true

cookie.path: ~
cookie.domain: ~
cookie.secure: false

trans.locale: "en_EN"

gzip.enabled: false