Adapter: "PostgreSQL"

Configuration:
    PostgreSQL:
        server: ~
        port: ~
        database_name: ~
        table_prefix: ~
        username: "postgres"
        password: "root"

    Travis:
        server: ~
        port: ~
        database_name: "travis_ci_test"
        table_prefix: ~
        username: "postgres"
        password: ~

    Tests:
        server: ~
        port: ~
        database_name: "tricolore_tests"
        table_prefix: ~
        username: "postgres"
        password: "root"